# Generated by Django 5.2.7 on 2025-10-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'Paypal'), ('bank', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instructor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('lecture_basic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.basiclecture')),
                ('lecture_clinical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.clinicallecture')),
            ],
        ),
    ]
