# Generated by Django 5.2.7 on 2025-11-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_alter_lectureprogress_basic_lecture_and_more'),
        ('payments', '0003_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.module'),
        ),
    ]
