# Generated by Django 5.2.7 on 2025-10-18 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_views_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitview',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_analytics', to='courses.courseunit'),
        ),
    ]
