# Generated by Django 5.2.7 on 2025-10-18 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('lectures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='related_basic_lectures',
            field=models.ManyToManyField(blank=True, related_name='cases_basic', to='lectures.basiclecture'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='related_clinical_lectures',
            field=models.ManyToManyField(blank=True, related_name='cases_clinical', to='lectures.clinicallecture'),
        ),
    ]
