# Generated by Django 5.2.7 on 2025-10-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='discipline_section',
            field=models.CharField(choices=[('anatomy', 'Anatomy'), ('embryology', 'Embryology'), ('histology', 'Histology'), ('physiology', 'Physiology'), ('pathology', 'Pathology'), ('pharmacology', 'Pharmacology')], default='anatomy', max_length=20),
        ),
    ]
