# Generated by Django 5.2.7 on 2025-10-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casestudy_discipline_section'),
        ('users', '0002_alter_courseproviderprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_created', to='users.user'),
        ),
    ]
