# Generated by Django 5.2.7 on 2025-10-23 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_casestudy_created_by'),
        ('lectures', '0005_remove_basiclecture_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='discipline_section',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='related_basic_lectures',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='related_clinical_lectures',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload supporting file (PDF, image, etc.)', null=True, upload_to='case_studies/files/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='lectures.basiclecture'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_studies', to='lectures.clinicallecture'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='discipline',
            field=models.CharField(choices=[('anatomy', 'Anatomy'), ('embryology', 'Embryology'), ('histology', 'Histology'), ('physiology', 'Physiology'), ('pathology', 'Pathology'), ('pharmacology', 'Pharmacology')], default='anatomy', max_length=20),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='case_studies/videos/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='video_url',
            field=models.URLField(blank=True, help_text='External or YouTube video link', null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
