# Generated by Django 5.2.7 on 2025-10-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_casestudy_discipline_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='discipline',
            field=models.CharField(choices=[('anatomy', 'Anatomy'), ('embryology', 'Embryology'), ('histology', 'Histology'), ('physiology', 'Physiology'), ('pathology', 'Pathology'), ('pharmacology', 'Pharmacology')], default='anatomy', max_length=50),
        ),
    ]
