# Generated by Django 5.2.7 on 2025-11-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_casestudy_discipline'),
        ('lectures', '0011_clinicallecture_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('discipline', models.CharField(choices=[('anatomy', 'Anatomy'), ('embryology', 'Embryology'), ('histology', 'Histology'), ('physiology', 'Physiology'), ('pathology', 'Pathology'), ('pharmacology', 'Pharmacology')], default='anatomy', max_length=50)),
                ('student_level', models.CharField(choices=[('year1', 'Year 1'), ('year2', 'Year 2'), ('year3', 'Year 3'), ('intern', 'Intern'), ('resident', 'Resident'), ('all', 'All Levels')], default='all', max_length=20)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('upcoming', 'Upcoming'), ('ended', 'Ended'), ('published', 'Published in Library')], default='pending', max_length=20)),
                ('video', models.FileField(blank=True, null=True, upload_to='case_studies/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies_new', to='lectures.basiclecture')),
                ('clinical_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies_new', to='lectures.clinicallecture')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_created_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseAttachmentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_studies/files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.casestudynew')),
            ],
        ),
    ]
