# Generated by Django 5.2.7 on 2025-11-27 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_casestudynew_caseattachmentnew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudynew',
            name='basic_lecture',
        ),
        migrations.RemoveField(
            model_name='casestudynew',
            name='clinical_lecture',
        ),
        migrations.RemoveField(
            model_name='casestudynew',
            name='created_by',
        ),
        migrations.CreateModel(
            name='CaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='cases.casestudy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_studies/attachments/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='CaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.casestudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='cases.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='CaseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cases.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_link', models.URLField()),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ended', 'Ended'), ('archived', 'Archived in Library')], default='upcoming', max_length=20)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='case_studies/recordings/')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cases.casestudy')),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='cases.casestudy')),
            ],
        ),
        migrations.DeleteModel(
            name='CaseAttachmentNew',
        ),
        migrations.DeleteModel(
            name='CaseStudyNew',
        ),
    ]
