# Generated by Django 5.2.7 on 2025-11-27 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_casestudynew_basic_lecture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseattachment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casecomment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='caselevel',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casequiz',
            name='case',
        ),
        migrations.RemoveField(
            model_name='casesession',
            name='case',
        ),
        migrations.RemoveField(
            model_name='learningobjective',
            name='case',
        ),
        migrations.CreateModel(
            name='CaseStudyNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('internal', 'Internal Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('obgyn', 'OB/GYN'), ('dermatology', 'Dermatology'), ('other', 'Other')], max_length=50)),
                ('target_level', models.CharField(help_text='Student level e.g. Year 1, Intern, Resident', max_length=50)),
                ('description', models.TextField()),
                ('learning_objectives', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='case_studies/pdf/')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='case_studies/images/')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('zoom_link', models.URLField()),
                ('session_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ended', 'Ended'), ('archived', 'Archived in Library')], default='upcoming', max_length=20)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='case_studies/recordings/')),
                ('recording_link', models.URLField(blank=True, null=True)),
                ('quiz', models.JSONField(blank=True, help_text='Optional quiz in JSON', null=True)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_studies_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_case_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CaseApproval',
        ),
        migrations.DeleteModel(
            name='CaseAttachment',
        ),
        migrations.DeleteModel(
            name='CaseComment',
        ),
        migrations.DeleteModel(
            name='CaseLevel',
        ),
        migrations.DeleteModel(
            name='CaseQuiz',
        ),
        migrations.DeleteModel(
            name='CaseSession',
        ),
        migrations.DeleteModel(
            name='LearningObjective',
        ),
    ]
