# Generated by Django 5.2.7 on 2025-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_remove_caseattachment_case_remove_casecomment_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudynew',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Is this case study paid?'),
        ),
        migrations.AddField(
            model_name='casestudynew',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Price if case study is paid', max_digits=8),
        ),
        migrations.AddField(
            model_name='casestudynew',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for case study', null=True, upload_to='case_studies/thumbnails/'),
        ),
    ]
