# Generated by Django 5.2.7 on 2025-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_casestudynew_is_paid_casestudynew_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudynew',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='casestudynew',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
