# Generated by Django 5.2.7 on 2025-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_remove_casestudynew_zoom_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudynew',
            name='zoom_meeting_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
