# Generated by Django 5.2.7 on 2025-10-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0002_alter_courseproviderprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_courses', to='users.user'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='users.user'),
        ),
        migrations.AlterField(
            model_name='courseview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views_courses', to='users.user'),
        ),
        migrations.AlterField(
            model_name='unitview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_views_courses', to='users.user'),
        ),
    ]
