# Generated by Django 5.2.7 on 2025-10-28 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_provider_alter_courseprogress_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unitview',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='courses.courseunit'),
        ),
    ]
