# Generated by Django 5.2.7 on 2025-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='course_content/'),
        ),
    ]
