# Generated by Django 5.2.7 on 2025-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_featured_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
