# Generated by Django 5.2.7 on 2025-11-05 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_quiz_max_attempts_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Minimum percentage required to pass this quiz', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
