# Generated by Django 5.2.7 on 2025-10-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoomAccount',
        ),
    ]
