# Generated by Django 5.2.7 on 2025-10-18 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basiclecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_lectures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.clinicalsystem'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='lectures.basicsystem'),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.discipline'),
        ),
        migrations.AddField(
            model_name='interactivenote',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.basiclecture'),
        ),
        migrations.AddField(
            model_name='interactivenote',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.clinicallecture'),
        ),
        migrations.AddField(
            model_name='interactivenote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicsystem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_systems', to='lectures.lecturecategory'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.basiclecture'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.clinicallecture'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lectures.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.basiclecture'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.clinicallecture'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lectures.quiz'),
        ),
    ]
