# Generated by Django 5.2.7 on 2025-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiclecture',
            name='video_url',
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
