# Generated by Django 5.2.7 on 2025-10-20 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_remove_basiclecture_video_url_and_more'),
        ('users', '0002_alter_courseproviderprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiclecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_lectures', to='users.user'),
        ),
        migrations.AlterField(
            model_name='clinicallecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_lectures', to='users.user'),
        ),
        migrations.AlterField(
            model_name='interactivenote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.user'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress', to='users.user'),
        ),
    ]
