# Generated by Django 5.2.7 on 2025-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_remove_basiclecture_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiclecture',
            name='zoom_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='zoom_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='zoom_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='zoom_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
