# Generated by Django 5.2.7 on 2025-10-30 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_zoomaccesslog'),
        ('payments', '0003_alter_payment_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paymob', 'Paymob'), ('paytabs', 'PayTabs'), ('tabby', 'Tabby / Tamara'), ('vodafone_cash', 'Vodafone Cash')], max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='basiclecture',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='basicsystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clinicallecture',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='clinicalsystem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='lecturecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='lectures/resources/'),
        ),
        migrations.AddField(
            model_name='basiclecture',
            name='video_storage_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clinicallecture',
            name='resources',
            field=models.FileField(blank=True, null=True, upload_to='lectures/resources/'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(default='Untitled Module', max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='total_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basiclecture',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_lectures', to='lectures.discipline'),
        ),
        migrations.AlterField(
            model_name='basiclecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basiclecture',
            name='lecture_type',
            field=models.CharField(choices=[('recorded', 'Recorded Video'), ('zoom', 'Live Zoom')], default='recorded', max_length=20),
        ),
        migrations.AlterField(
            model_name='basiclecture',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lectures.module'),
        ),
        migrations.AlterField(
            model_name='clinicallecture',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicallecture',
            name='lecture_type',
            field=models.CharField(choices=[('recorded', 'Recorded Video'), ('zoom', 'Live Zoom')], default='recorded', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicallecture',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='lectures.module'),
        ),
        migrations.AlterField(
            model_name='interactivenote',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.basiclecture'),
        ),
        migrations.AlterField(
            model_name='interactivenote',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lectures.clinicallecture'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lectures.basiclecture'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lectures.clinicallecture'),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lectures.basiclecture'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lectures.clinicallecture'),
        ),
        migrations.AlterUniqueTogether(
            name='basicsystem',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('system', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('student', 'basic_lecture'), ('student', 'clinical_lecture')},
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='lectures.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.CreateModel(
            name='InstructorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.module')),
            ],
        ),
        migrations.CreateModel(
            name='LectureReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basic_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lectures.basiclecture')),
                ('clinical_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lectures.clinicallecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lectures.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_basic_lectures', models.ManyToManyField(blank=True, related_name='+', to='lectures.basiclecture')),
                ('completed_clinical_lectures', models.ManyToManyField(blank=True, related_name='+', to='lectures.clinicallecture')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lectures.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lectures.module')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='payments.payment')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectures.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='lectures.basiclecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ZoomAccessLog',
        ),
        migrations.AddIndex(
            model_name='lecturereview',
            index=models.Index(fields=['rating'], name='lectures_le_rating_430707_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleenrollment',
            unique_together={('student', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('student', 'module')},
        ),
        migrations.AddIndex(
            model_name='videoaccesstoken',
            index=models.Index(fields=['token'], name='lectures_vi_token_c8fa80_idx'),
        ),
    ]
