# Generated by Django 5.2.7 on 2025-11-08 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0009_quizattempt_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureprogress',
            name='basic_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.basiclecture'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='clinical_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lectures.clinicallecture'),
        ),
    ]
