# Generated by Django 5.2.7 on 2025-11-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0010_alter_lectureprogress_basic_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicallecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
